name: Ruby Gem Test

on:
  push:
    branches: [ main, test-workflow ]
  pull_request:
    branches: [ main, test-workflow ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.3', '3.0.6']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Install Jeweler
      run: gem install jeweler

    - name: Install libyaml for sdoc
      run: sudo apt-get install libyaml-dev

    - name: Set up dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake
